source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Eventitic_Example', :exclusive => true do
  pod 'Eventitic', :path => '../'
end

target 'Eventitic_Tests', :exclusive => true do
  pod 'Eventitic', :path => '../'

  
end
