source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Eventitic_Tests', :exclusive => true do
  pod "Eventitic", :path => "../"

  pod 'Quick', '~> 0.9.2'
  pod 'Nimble', '4.0.0'
end
