# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Eventitic_iOS' do

end

target 'EventiticTests_iOS' do
  pod 'Nimble', '4.0.0'
end

target 'Eventitic_OSX' do

end

target 'Eventitic_watchOS' do

end

target 'Eventitic_tvOS' do

end

